### PR TITLE
1st french adjusts

### PR DESCRIPTION
**Pull request by lyonelf**
## Test Plan
2023-03-14_18h25_47

Some lines are not "translatable" in git

### CODE REVIEW

**Comment by abhinavkgrd** [comment]
From the code, it doesn't look like you have translated any of those strings ,they are still the same, 
you have fixed your mistakes in other stuff.

Just in case you weren't able to find them these are the three new strings 

image 

``` WHERE_YOUR_BEST_PHOTOS_LIVE: 'Where your best photos live',```

``` IMPORT_YOUR_FOLDERS: 'Import your folders',```

Hope this helps, Thanks again.!! 😄

**Comment by lyonelf** [comment]
i don't find anything in the file located here:
image

**Comment by abhinavkgrd** [comment]
Ohh, yes these are missing from the frenchConstants. As these were added after the initial french translation was.

The English version of them is present in the englistConstants file

you can create new entries in the frenchConstants file for them

**Comment by lyonelf** [comment]
done it

ready for the pull

**Review by abhinavkgrd — APPROVED** [review]

**Pull request merged**
