### PR TITLE
Update translation.json

### PR DESCRIPTION
**Pull request by lyonelf**

### CODE REVIEW

**Comment by abhinavkgrd** [comment]
Hi @lyonelf, so, we have now set-up, a `crowdin` [project](https://crowdin.com/project/ente-photos-web) for managing translations.

You can now use that to add translation 😄. It provides a much better interface and no need to manually look through files to see what strings are missing.

**Comment by abhinavkgrd** [comment]
Yes, There were a few other strings (related to export flow), but it looks like you have translated them too.
So, yes nothing else... you have translated them all 🥳

**Comment by abhinavkgrd** [comment]
If you are craving more 😜  you can translate the ente auth app too, https://crowdin.com/project/ente-authenticator-app

**Comment by lyonelf** [comment]
let's go

and after that, the mobile app ;)

**Review by abhinavkgrd — APPROVED** [review]

**Pull request merged**
